<?php
/**
 * @file
 * db_markdown.module
 */

/**
 * Implements hook_filter_info().
 */
function db_markdown_filter_info() {
  $filters['parsedown_extra'] = array(
    'title' => t('ParsedownExtra'),
    'process callback' => '_db_markdown_filter_process',
    'tips callback' => '_db_markdown_filter_tip',
  );
  return $filters;
}

/**
 * Callback for processing the "parsedown_extra" filter.
 */
function _db_markdown_filter_process($text) {
  $parser = new ParsedownExtra();
  return $parser->text($text);
}

/**
 * Implements callback_filter_tips().
 *
 * Provides help for the auto-paragraph filter.
 *
 * @see filter_filter_info()
 */
function _db_markdown_filter_tip($filter, $format, $long = FALSE) {
  $description = t('Parses text using the <a href="http://parsedown.org/" target="_blank">Parsedown</a> and <a href="https://packagist.org/packages/erusev/parsedown-extra" target="_blank">ParsedownExtra</a> libraries.');
  if (!$long) {
    return $description;
  }
  $options = array(
    'external' => TRUE,
    'attributes' => array(
      'target' => '_blank',
    ),
  );
  $tips = array(
    l(t('Markdown: By John Gruber'), 'http://daringfireball.net/projects/markdown/', $options),
    l(t('GitHub Flavored Markdown'), 'https://help.github.com/articles/github-flavored-markdown/', $options),
  );
  return $description . '<br><br>For examples on usage, visit:<br><ul><li>' . implode('</li><li>', $tips) . '</li></ul>';
}
