<?php
/**
 * @file
 * db_markdown.module
 */

use Drupal\DBMarkdown\DBMarkdown;

/**
 * Remove an entire preg_match string from a string.
 *
 * @param string $string
 *   The string to remove match from, passed by reference.
 * @param array $matches
 *   The matches from preg_match.
 * @param string $replace
 *   The string to replace match with.
 */
function _db_markdown_replace_preg_match(&$string, array $matches, $replace = '') {
  $string = preg_replace('/' . preg_quote($matches[0], '/') . '/Us', $replace, $string);
}

/**
 * Implements hook_filter_info().
 */
function db_markdown_filter_info() {
  $filters['parsedown_extra'] = array(
    'title' => t('ParsedownExtra'),
    'process callback' => 'db_markdown_parse_text',
    'tips callback' => '_db_markdown_filter_tip',
  );
  return $filters;
}

/**
 * Parses a string with the Parsedown Extra library.
 *
 * @param string $string
 *   The string to parse.
 *
 * @return string
 *   The parsed string.
 */
function db_markdown_parse_text($string) {
  static $parsedown;
  if (!isset($parsedown)) {
    $parsedown = new DBMarkdown();
  }
  return $parsedown->text($string);
}

/**
 * Implements callback_filter_tips().
 *
 * Provides help for the auto-paragraph filter.
 *
 * @see filter_filter_info()
 */
function _db_markdown_filter_tip($filter, $format, $long = FALSE) {
  $description = t('Parses text using the <a href="http://parsedown.org/" target="_blank">Parsedown</a> and <a href="https://packagist.org/packages/erusev/parsedown-extra" target="_blank">ParsedownExtra</a> libraries.');
  if (!$long) {
    return $description;
  }
  $options = array(
    'external' => TRUE,
    'attributes' => array(
      'target' => '_blank',
    ),
  );
  $tips = array(
    l(t('Markdown: By John Gruber'), 'http://daringfireball.net/projects/markdown/', $options),
    l(t('GitHub Flavored Markdown'), 'https://help.github.com/articles/github-flavored-markdown/', $options),
  );
  return $description . '<br><br>For examples on usage, visit:<br><ul><li>' . implode('</li><li>', $tips) . '</li></ul>';
}
